name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.2.0
  provider: ^6.1.5
  google_fonts: ^6.2.1
  flutter_tts: ^4.2.3
  speech_to_text: ^7.2.0
  geolocator: ^14.0.2
  image_picker: ^1.1.2
  fl_chart: ^0.68.0
  lucide_icons: ^0.257.0
  shared_preferences: ^2.5.3
  camera: ^0.11.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  intl: ^0.19.0
  flutter_svg: ^2.2.0
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
